{% set name = "rich-rst" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be57b3ec142761a51186fa3aa9852fc92aef387b407fcc42eb5bc6820b82d485

build:
  noarch: python
  number: 0
  script_env: PYTHONUTF8=1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rich >=12.0.0
    - docutils

test:
  imports:
    - rich_rst

about:
  home: https://rich-rst.readthedocs.io
  summary: A reStructuredText renderer for rich
  keywords: python cli sphinx python3 restructuredtext rich rst docutils command-line-interface
  dev_url: https://github.com/wasi-master/rich-rst
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
